=== ajduet/assignforce-v3/local-dev/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "batches": {
      "type": "array",
      "items": {}
    },
    "curricula": {
      "type": "array",
      "items": {}
    },
    "trainers": {
      "type": "array",
      "items": {}
    },
    "skills": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            },
            "tags": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                },
                {
                  "type": "string"
                },
                {
                  "type": "string"
                }
              ]
            }
          },
          "required": ["id", "name", "tags"]
        }
      ]
    },
    "locations": {
      "type": "array",
      "items": {}
    },
    "buildings": {
      "type": "array",
      "items": {}
    },
    "rooms": {
      "type": "array",
      "items": {}
    },
    "projects": {
      "type": "array",
      "items": {}
    },
    "settings": {
      "type": "array",
      "items": {}
    }
  },
  "required": [
    "batches",
    "curricula",
    "trainers",
    "skills",
    "locations",
    "buildings",
    "rooms",
    "projects",
    "settings"
  ]
}

=== ajduet/assignforce-v3/local-dev/db.json
{
  "$schema": "./schema.json",
  "batches": [],
  "curricula": [],
  "trainers": [],
  "skills": [
    {
      "id": 1,
      "name": "Java",
      "tags": ["Core", "Java", "OOP"]
    },
    {
      "id": 2,
      "name": "C#",
      "tags": ["Core", "C#", "OOP"]
    },
    {
      "id": 3,
      "name": "SQL",
      "tags": ["Core", "RDBMS", "Data"]
    },
    {
      "id": 4,
      "name": "Oracle SQL",
      "tags": ["Core", "RDBMS", "Data"]
    },
    {
      "id": 5,
      "name": "PostreSQL",
      "tags": ["Core", "RDBMS", "Data"]
    }
  ],
  "locations": [],
  "buildings": [],
  "rooms": [],
  "projects": [],
  "settings": []
}
